name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build the project and run tests
        run: |
          xcodebuild test \
            -scheme rxsnippet \
            -allowProvisioningUpdates \
            -skipPackagePluginValidation \
            CODE_SIGN_IDENTITY=- \
            CODE_SIGNING_REQUIRED=NO \
            | xcpretty && exit ${PIPESTATUS[0]}
